version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: poo-app
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: poo-nginx
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: app-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

